version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: quiz-postgres
    ports:
      - '35432:5432'
    environment:
      POSTGRES_DB: quiz_builder_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
